"""Callable-first normalization API."""

from extractory.normalization.builtins import (
    BooleanNormalizer,
    CascadingSelectNormalizer,
    ComponentArrayNormalizer,
    DateNormalizer,
    DatetimeNormalizer,
    DelimitedTextArrayNormalizer,
    IdentityNormalizer,
    IssueKeyExtractNormalizer,
    JiraIssueLinksNormalizer,
    JiraSprintNormalizer,
    JiraUserArrayNormalizer,
    JiraUserNormalizer,
    LabelsNormalizer,
    NamedArrayNormalizer,
    NamedObjectNormalizer,
    NumberNormalizer,
    OptionArrayNormalizer,
    OptionNormalizer,
    RawJsonNormalizer,
    RegexExtractNormalizer,
    StringNormalizer,
    TextNormalizer,
    VersionArrayNormalizer,
)
from extractory.normalization.context import (
    FieldNormalizationContext,
    FieldNormalizationResult,
    FieldNormalizer,
)
from extractory.normalization.gerrit import normalize_gerrit_change
from extractory.normalization.jira import normalize_jira_issue
from extractory.normalization.registry import (
    ConflictPolicy,
    ErrorPolicy,
    FieldNormalizerRegistry,
)
from extractory.normalization.result import NormalizationResult

__all__ = [
    "BooleanNormalizer",
    "CascadingSelectNormalizer",
    "ComponentArrayNormalizer",
    "ConflictPolicy",
    "DateNormalizer",
    "DatetimeNormalizer",
    "DelimitedTextArrayNormalizer",
    "ErrorPolicy",
    "FieldNormalizationContext",
    "FieldNormalizationResult",
    "FieldNormalizer",
    "FieldNormalizerRegistry",
    "IdentityNormalizer",
    "IssueKeyExtractNormalizer",
    "JiraIssueLinksNormalizer",
    "JiraSprintNormalizer",
    "JiraUserArrayNormalizer",
    "JiraUserNormalizer",
    "LabelsNormalizer",
    "NamedArrayNormalizer",
    "NamedObjectNormalizer",
    "NormalizationResult",
    "NumberNormalizer",
    "OptionArrayNormalizer",
    "OptionNormalizer",
    "RawJsonNormalizer",
    "RegexExtractNormalizer",
    "StringNormalizer",
    "TextNormalizer",
    "VersionArrayNormalizer",
    "normalize_gerrit_change",
    "normalize_jira_issue",
]
